### ISSUE TITLE
termux上运行的问题

### ISSUE THREAD

**Issue by zhnlanf** [Hydrahail-Johnson/diy_scripts#1]
大佬，我是在termux上运行报错
![image](https://user-images.githubusercontent.com/58921007/111761521-f5062200-88da-11eb-96e6-88714a52ae6c.png)
然后我把diy.sh里面的
![image](https://user-images.githubusercontent.com/58921007/111761628-11a25a00-88db-11eb-8f84-8cf90f600f3a.png)
/jd/config/crontab.list前面加个~之后可以正常运行

**Comment by zhnlanf** [comment]
我把自动更新diy.sh部分注释掉了
以及定时任务的格式，我也修改了，使用termux的朋友得注意一下

**Comment by Hydrahail-Johnson** [comment]
来来来，加我qq 547302754，验证id写你的github，我把大佬的qq推给你，这个是我们群大佬写的，我只是提供了一个库帮大佬存

**Comment by qiao112** [comment]
> 我把自动更新diy.sh部分注释掉了
> 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
修复了使用最新的试试

**Comment by zhnlanf** [comment]
> > 我把自动更新diy.sh部分注释掉了
> > 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
> > 修复了使用最新的试试

不报错了，但是定时任务的格式docker和termux不同
termux是这种：
4 0,9 * * * bash /data/data/com.termux/files/home/jd/jd.sh jd_bean_sign

**Comment by qiao112** [comment]
> > > 我把自动更新diy.sh部分注释掉了
> > > 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
> > > 修复了使用最新的试试
> 
> 不报错了，但是定时任务的格式docker和termux不同
> termux是这种：
> 4 0,9 * * * bash /data/data/com.termux/files/home/jd/jd.sh jd_bean_sign

这就要你们自己改了不做适配了

**Comment by zhnlanf** [comment]
> > > > 我把自动更新diy.sh部分注释掉了
> > > > 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
> > > > 修复了使用最新的试试
> > 
> > 
> > 不报错了，但是定时任务的格式docker和termux不同
> > termux是这种：
> > 4 0,9 * * * bash /data/data/com.termux/files/home/jd/jd.sh jd_bean_sign
> 
> 这就要你们自己改了不做适配了

好的，谢谢

**Comment by qiao112** [comment]
> > > > > 我把自动更新diy.sh部分注释掉了
> > > > > 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
> > > > > 修复了使用最新的试试
> > > 
> > > 
> > > 不报错了，但是定时任务的格式docker和termux不同
> > > termux是这种：
> > > 4 0,9 * * * bash /data/data/com.termux/files/home/jd/jd.sh jd_bean_sign
> > 
> > 
> > 这就要你们自己改了不做适配了
> 
> 好的，谢谢

![image](https://user-images.githubusercontent.com/45731546/111803767-54c7f180-890a-11eb-9023-a2e8a4ba1ec2.png)
其实改一下这三个地方就好了

**Comment by zhnlanf** [comment]
> > > > > > 我把自动更新diy.sh部分注释掉了
> > > > > > 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
> > > > > > 修复了使用最新的试试
> > > > 
> > > > 
> > > > 不报错了，但是定时任务的格式docker和termux不同
> > > > termux是这种：
> > > > 4 0,9 * * * bash /data/data/com.termux/files/home/jd/jd.sh jd_bean_sign
> > > 
> > > 
> > > 这就要你们自己改了不做适配了
> > 
> > 
> > 好的，谢谢
> 
> ![image](https://user-images.githubusercontent.com/45731546/111803767-54c7f180-890a-11eb-9023-a2e8a4ba1ec2.png)
> 其实改一下这三个地方就好了

对，这个我知道，就是我得注释掉更新diy.sh部分

**Comment by qiao112** [comment]
> > > > > > > 我把自动更新diy.sh部分注释掉了
> > > > > > > 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
> > > > > > > 修复了使用最新的试试
> > > > > 
> > > > > 
> > > > > 不报错了，但是定时任务的格式docker和termux不同
> > > > > termux是这种：
> > > > > 4 0,9 * * * bash /data/data/com.termux/files/home/jd/jd.sh jd_bean_sign
> > > > 
> > > > 
> > > > 这就要你们自己改了不做适配了
> > > 
> > > 
> > > 好的，谢谢
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/45731546/111803767-54c7f180-890a-11eb-9023-a2e8a4ba1ec2.png)
> > 其实改一下这三个地方就好了
> 
> 对，这个我知道，就是我得注释掉更新diy.sh部分

可以定期看一下是非有更新就可以了,对了问一句怎么知道的这个库

**Comment by zhnlanf** [comment]
> > > > > > > > 我把自动更新diy.sh部分注释掉了
> > > > > > > > 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
> > > > > > > > 修复了使用最新的试试
> > > > > > 
> > > > > > 
> > > > > > 不报错了，但是定时任务的格式docker和termux不同
> > > > > > termux是这种：
> > > > > > 4 0,9 * * * bash /data/data/com.termux/files/home/jd/jd.sh jd_bean_sign
> > > > > 
> > > > > 
> > > > > 这就要你们自己改了不做适配了
> > > > 
> > > > 
> > > > 好的，谢谢
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/45731546/111803767-54c7f180-890a-11eb-9023-a2e8a4ba1ec2.png)
> > > 其实改一下这三个地方就好了
> > 
> > 
> > 对，这个我知道，就是我得注释掉更新diy.sh部分
> 
> 可以定期看一下是非有更新就可以了,对了问一句怎么知道的这个库

库主人有在水果群发过链接

**Comment by qiao112** [comment]
> > > > > > > > > 我把自动更新diy.sh部分注释掉了
> > > > > > > > > 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
> > > > > > > > > 修复了使用最新的试试
> > > > > > > 
> > > > > > > 
> > > > > > > 不报错了，但是定时任务的格式docker和termux不同
> > > > > > > termux是这种：
> > > > > > > 4 0,9 * * * bash /data/data/com.termux/files/home/jd/jd.sh jd_bean_sign
> > > > > > 
> > > > > > 
> > > > > > 这就要你们自己改了不做适配了
> > > > > 
> > > > > 
> > > > > 好的，谢谢
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/45731546/111803767-54c7f180-890a-11eb-9023-a2e8a4ba1ec2.png)
> > > > 其实改一下这三个地方就好了
> > > 
> > > 
> > > 对，这个我知道，就是我得注释掉更新diy.sh部分
> > 
> > 
> > 可以定期看一下是非有更新就可以了,对了问一句怎么知道的这个库
> 
> 库主人有在水果群发过链接

好的,低调使用

**Comment by zhnlanf** [comment]
> > > > > > > > > > 我把自动更新diy.sh部分注释掉了
> > > > > > > > > > 以及定时任务的格式，我也修改了，使用termux的朋友得注意一下
> > > > > > > > > > 修复了使用最新的试试
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不报错了，但是定时任务的格式docker和termux不同
> > > > > > > > termux是这种：
> > > > > > > > 4 0,9 * * * bash /data/data/com.termux/files/home/jd/jd.sh jd_bean_sign
> > > > > > > 
> > > > > > > 
> > > > > > > 这就要你们自己改了不做适配了
> > > > > > 
> > > > > > 
> > > > > > 好的，谢谢
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/45731546/111803767-54c7f180-890a-11eb-9023-a2e8a4ba1ec2.png)
> > > > > 其实改一下这三个地方就好了
> > > > 
> > > > 
> > > > 对，这个我知道，就是我得注释掉更新diy.sh部分
> > > 
> > > 
> > > 可以定期看一下是非有更新就可以了,对了问一句怎么知道的这个库
> > 
> > 
> > 库主人有在水果群发过链接
> 
> 好的,低调使用

好的🤭
